# Generated by Django 6.0.5 on 2026-09-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_file'),
        ('projects', '0002_alter_project_start_date_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_logo', to='files.file'),
        ),
    ]
