# Generated by Django 6.0.5 on 2026-06-19 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('MESSAGE', 'Message'), ('TASK', 'Task'), ('TASK_COMMENT', 'Task Comment')], max_length=20)),
                ('resource_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('ARCHIVE', 'Archive'), ('OTHER', 'Other')], max_length=20)),
                ('extension', models.CharField(editable=False, max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
