# Generated by Django 6.0.5 on 2026-06-19 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='fileattach',
            name='attached_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileattach',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='files.file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['workspace'], name='files_file_workspa_998a74_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by'], name='files_file_uploade_b6f406_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_deleted'], name='files_file_is_dele_6ea6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattach',
            index=models.Index(fields=['resource_type', 'resource_id'], name='files_filea_resourc_f3e585_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattach',
            index=models.Index(fields=['file'], name='files_filea_file_id_b1ea42_idx'),
        ),
        migrations.AddIndex(
            model_name='fileattach',
            index=models.Index(fields=['attached_by'], name='files_filea_attache_64a27f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileattach',
            constraint=models.UniqueConstraint(fields=('file', 'resource_type', 'resource_id'), name='unique_file_attachment'),
        ),
    ]
