# Generated by Django 6.0.5 on 2026-07-17 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMMENT', 'Task Comment'), ('TASK_DUE', 'Task Due'), ('TASK_OVERDUE', 'Task Overdue'), ('PROJECT_ADDED', 'Project Added'), ('PROJECT_INVITATION', 'Project Invitation'), ('WORKSPACE_INVITATION', 'Workspace Invitation'), ('MENTION', 'Mention'), ('OWNERSHIP_TRANSFER', 'Ownership Transfer')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('TASK', 'Task'), ('PROJECT', 'Project'), ('MESSAGE', 'Message'), ('INVITATION', 'Invitation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
    ]
