# Generated by Django 6.0.5 on 2026-06-19 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('WORKSPACE_CREATED', 'Workspace Created'), ('WORKSPACE_UPDATED', 'Workspace Updated'), ('WORKSPACE_MEMBER_ADDED', 'Workspace Member Added'), ('WORKSPACE_MEMBER_REMOVED', 'Workspace Member Removed'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_ARCHIVED', 'Project Archived'), ('TASK_CREATED', 'Task Created'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('COMMENT_ADDED', 'Comment Added'), ('FILE_UPLOADED', 'File Uploaded'), ('INVITATION_SENT', 'Invitation Sent'), ('INVITATION_ACCEPTED', 'Invitation Accepted')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('WORKSPACE', 'Workspace'), ('PROJECT', 'Project'), ('TASK', 'Task'), ('COMMENT', 'Comment'), ('FILE', 'File'), ('INVITATION', 'Invitation')], max_length=20)),
                ('resource_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
