# Generated by Django 6.0.5 on 2026-06-19 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['workspace'], name='audit_event_workspa_90df49_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['actor'], name='audit_event_actor_i_76b151_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type'], name='audit_event_event_t_6a11cd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='audit_event_resourc_825ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['created_at'], name='audit_event_created_af4006_idx'),
        ),
    ]
