# Generated by Django 6.0.5 on 2026-07-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsmodel',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
