# Generated by Django 6.0.5 on 2026-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sessionsmodel_last_active_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingsmodel',
            name='dm_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettingsmodel',
            name='mention_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettingsmodel',
            name='task_notifications',
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='email_mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='email_task_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='email_workspace_invitations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='inapp_mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='inapp_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='inapp_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettingsmodel',
            name='inapp_workspaces',
            field=models.BooleanField(default=False),
        ),
    ]
